### ISSUE TITLE
assertIsNotNone does not work with python 2.6

### ISSUE THREAD

**Issue by uolter** [uolter/redis_failover#2]
Traceback (most recent call last):
  File "test_cluster.py", line 77, in test_promote_new_master_single_node
    self.assertIsNotNone(node)
AttributeError: 'TestCluster' object has no attribute 'assertIsNotNone'

**Comment by mkjsix** [comment]
Fixed Python 2.6 changing line 77 to: self.assertTrue(node is not None)
